### ISSUE TITLE
"Not supported browser" 

### ISSUE THREAD

**Issue by Glass47** [Kizuno18/Twitch-view-bot#1]
![image](https://user-images.githubusercontent.com/55170107/206165111-eaf08873-bf5c-451f-9963-6926f210e9bc.png)
Seems like that twitch anti-bot BS is not allowing me to log in, if you can fix it i want to try it :]

**Comment by Kizuno18** [comment]
i can fix it, but just out of time, this repository is to aim learning purpouses.
